
export CO="/Users/ellie/Documents/RPI/Classes/CompOrg"
export DS="/Users/ellie/Documents/RPI/Classes/dataStructures"
export DSL="/Users/ellie/Documents/RPI/Classes/dataStructures/lectures"
export DSC="/Users/ellie/Documents/RPI/Classes/dataStructures/mentoring/hw06_contest_2023"
export SKX="/Users/ellie/Documents/Programming/skewax/RCOS"
export OBS="/Users/ellie/Library/Mobile Documents/iCloud~md~obsidian/Documents/Main Vault"
export PSITE="/Users/ellie/Documents/Programming/personalSite"
export ESPANSO="/Users/ellie/Library/Application Support/espanso"
export PRG="/Users/ellie/Documents/Programming"
export AVC="/Users/ellie/.config/nvim/lua/user/init.lua"
export IES="/Users/ellie/Documents/Work/IES/code.nosync"
export AL="/Users/ellie/Documents/RPI/Classes/algo"
export NC="/Users/ellie/Documents/RPI/Classes/NumComp"
export PS="/Users/ellie/Documents/RPI/Classes/PSoft"
